name: Build and Publish to Modrinth

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up SDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - run: chmod +x ./gradlew

      - name: Test
        run: ./gradlew test

      - name: Build
        run: ./gradlew build

      - name: Publish on Modrinth
        run: ./gradlew modrinth
