name: Generate Documentation

on:
  workflow_run:
    types:
      - completed
    workflows:
      - build
    branches:
      - "**"

jobs:
  doc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}

      - name: Set up SDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - run: chmod +x ./gradlew

      - name: Generate documentation
        run: ./gradlew dokkaHtml

      - name: Release documentation
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/dokka
